apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-ps-deploy
  labels:
    app: bankapp-ps-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-ps-app
  template:
    metadata:
      labels:
        app: bankapp-ps-app
    spec:
      containers:
      - name: bankapp-ps-container
        image: prathamesh78/bankapp-ps-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-ps-np-service
  labels:
    app: bankapp-ps-app
spec:
  selector:
    app: bankapp-ps-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
